const A={q:[],s:[],t:[],m:{},c:{},name:'',i:0,a:[],score:{}};const $=id=>document.getElementById(id);const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
async function init(){const [q,s,t,m,c]=await Promise.all(['questions','stats','types','messages','config'].map(x=>fetch(`data/${x}.json`).then(r=>r.json())));A.q=q;A.s=s.stats;A.t=t.types;A.m=m;A.c=c;reset()}
function reset(){A.score={};A.s.forEach(x=>A.score[x.id]=0)}function screen(x){document.querySelectorAll('.screen').forEach(e=>e.classList.remove('on'));$(x).classList.add('on');scrollTo(0,0)}
function start(){A.name=$('name').value.trim();if(!A.name)return toast('アカウント名を入力してください');A.i=0;A.a=[];reset();draw();screen('quiz')}
function draw(){$('qn').textContent=`Q${A.i+1}`;$('pct').textContent=`${Math.round((A.i+1)/A.q.length*100)}%`;$('bar').style.width=`${(A.i+1)/A.q.length*100}%`;const q=A.q[A.i];$('qt').textContent=q.text;$('choices').innerHTML=q.choices.map(c=>`<button class="choice" data-id="${c.id}"><span class="letter">${c.id}</span><span>${esc(c.text)}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(q,b.dataset.id));$('back').style.display=A.i?'inline-block':'none'}
function apply(e,m){Object.entries(e||{}).forEach(([k,v])=>A.score[k]=(A.score[k]||0)+v*m)}function answer(q,id){if(A.a[A.i]){const old=q.choices.find(x=>x.id===A.a[A.i]);if(old)apply(old.effects,-1)}A.a[A.i]=id;const c=q.choices.find(x=>x.id===id);apply(c.effects,1);if(A.i===A.q.length-1)result();else{A.i++;draw()}}
function back(){if(!A.i)return;A.i--;reset();A.a.slice(0,A.i).forEach((id,i)=>{const c=A.q[i].choices.find(x=>x.id===id);if(c)apply(c.effects,1)});draw()}
function normalized(){const vals=A.s.map(x=>A.score[x.id]||0), max=Math.max(10,...vals.map(v=>Math.abs(v))),o={};A.s.forEach(x=>o[x.id]=Math.round(clamp(50+(A.score[x.id]||0)/max*50)));return o}
function fit(t,s){let tw=0,v=0;Object.entries(t.weights||{}).forEach(([k,w])=>{tw+=Math.abs(w);v+=(s[k]||50)*w});let f=tw?v/tw:50;(t.required||[]).forEach(r=>{if((s[r.stat]||0)<r.min)f-=(r.min-(s[r.stat]||0))*.7});(t.bonuses||[]).forEach(b=>{if((s[b.stat]||0)>=b.min)f+=b.bonus});return Math.round(clamp(f))}
function result(){const s=normalized(),rank=A.t.map(t=>({t,f:fit(t,s)})).sort((a,b)=>b.f-a.f||a.t.priority-b.t.priority),w=rank[0];const r=w.t.result||{};$('rname').textContent=A.name;$('rtype').textContent=w.t.name;$('catch').textContent=`「${w.t.catchphrase}」`;$('fit').textContent=w.f;$('desc').textContent=r.description||'';$('advice').textContent=r.advice||'';$('caution').textContent=r.caution||'';$('shareText').textContent=A.m.shareTemplate.replace('{name}',A.name).replace('{type}',w.t.name);let ss=A.s.map(x=>({n:x.name,id:x.id,v:s[x.id]||50})).sort((a,b)=>b.v-a.v);$('stats').innerHTML=ss.slice(0,6).map(x=>`<div class="stat"><span>${esc(x.n)}</span><div class="statbar"><div style="width:${x.v}%"></div></div><b>${x.v}</b></div>`).join('');let hs=(A.m.hiddenStats||[]).map(x=>({n:x.name,v:Math.round((x.formula||[]).reduce((z,k)=>z+(s[k]??50),0)/Math.max(1,x.formula.length))})).sort((a,b)=>b.v-a.v).slice(0,5);$('hidden').innerHTML=hs.map(x=>`<div class="hs"><span>${esc(x.n)}</span><b>${x.v}</b></div>`).join('');$('runner').innerHTML=rank.slice(1,3).map(x=>`<div class="runner"><span>${esc(x.t.name)}</span><b>${x.f}%</b></div>`).join('');A.last={w,s};screen('result')}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(x){const t=$('toast');t.textContent=x;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function download(){const c=document.createElement('canvas'),ctx=c.getContext('2d'),w=900,h=1250;c.width=w*2;c.height=h*2;ctx.scale(2,2);ctx.fillStyle='#fffaf5';ctx.fillRect(0,0,w,h);ctx.fillStyle='#e85d04';ctx.fillRect(0,0,w,90);ctx.fillStyle='#fff';ctx.font='900 30px sans-serif';ctx.fillText('スプナータイプ辛口診断',45,58);ctx.fillStyle='#24160f';ctx.font='700 24px sans-serif';ctx.fillText(`${A.name}さんは`,45,145);ctx.fillStyle='#e85d04';ctx.font='900 48px sans-serif';wrap(ctx,$('rtype').textContent,45,215,810,60);ctx.fillStyle='#24160f';ctx.font='700 22px sans-serif';wrap(ctx,$('catch').textContent,45,330,810,32);ctx.font='800 24px sans-serif';ctx.fillText(`適合度 ${$('fit').textContent}%`,45,405);let y=465;[['あなたの生態',$('desc').textContent],['裏ステータス',$('hidden').innerText.replaceAll('\n',' / ')],['アドバイス',$('advice').textContent],['注意点',$('caution').textContent]].forEach(([h,t])=>{ctx.fillStyle='#e85d04';ctx.font='900 23px sans-serif';ctx.fillText(h,45,y);y+=36;ctx.fillStyle='#24160f';ctx.font='500 19px sans-serif';y=wrap(ctx,t,45,y,810,30)+25});ctx.fillStyle='#78675e';ctx.font='14px sans-serif';ctx.fillText('非公式ファンメイド診断 / SPOON運営とは関係ありません',45,h-25);const a=document.createElement('a');a.download=`spoon-type-${A.name}.png`;a.href=c.toDataURL('image/png');a.click();toast('結果画像を保存しました！')}
function wrap(ctx,t,x,y,mw,lh){let line='';for(const w of String(t).split(/\s+/)){const z=line?line+' '+w:w;if(ctx.measureText(z).width>mw&&line){ctx.fillText(line,x,y);y+=lh;line=w}else line=z}if(line){ctx.fillText(line,x,y);y+=lh}return y}
async function share(){const text=$('shareText').textContent+'\n'+location.href;if(navigator.share){try{await navigator.share({title:'スプナータイプ辛口診断',text})}catch(e){}}else{try{await navigator.clipboard.writeText(text);toast('シェア文をコピーしました！')}catch(e){toast('コピーできませんでした')}}}
$('startBtn').onclick=start;$('name').onkeydown=e=>{if(e.key==='Enter')start()};$('back').onclick=back;$('download').onclick=download;$('share').onclick=share;$('retry').onclick=()=>{A.i=0;A.a=[];reset();$('name').value=A.name;screen('start')};init().catch(e=>{console.error(e);toast('診断データを読み込めませんでした')});
